#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Science, Statistics, and Life

# Short bio or description (displayed in the header)
description: Tutorials on statistics, musings about science, and thoughts on life.

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: lwjohnst@gmail.com
  facebook:
  flickr:
  github: lwjohnst86
  instagram:
  linkedin:
  pinterest:
  rss: yes
  twitter: lwjohnst
  youtube:
  stackoverflow: users/2632184/luke
# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: lwjohnst86

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-58165822-1

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: http://blog.lukewjohnston.com

markdown: kramdown ##redcarpet
permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.1.0

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins

# Exclude these files from your production _site
exclude:
    - LICENSE.md
    - README.md
    - knitpost.R
    - blog.Rproj

